### ISSUE TITLE
v15启动报错

### ISSUE THREAD

**Issue by bokire** [worktile/ngx-planet#278]
**Describe the bug**
下载仓库代码，安装启动报错

**To Reproduce**
1. git clone https://github.com/worktile/ngx-planet.git
2. npm i
3. npm run start

**Expected behavior**
TypeError: The 'compilation' argument must be an instance of Compilation
    at Function.getCompilationHooks (/Users/bokire/git/ngx-planet/node_modules/webpack/lib/NormalModule.js:227:10)
    at WebpackAssetsManifest.handleCompilation (/Users/bokire/git/ngx-planet/node_modules/webpack-assets-manifest/src/WebpackAssetsManifest.js:784:18)
    at Hook.eval [as call] (eval at create (/Users/bokire/git/ngx-planet/node_modules/@angular-devkit/build-angular/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:230:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/bokire/git/ngx-planet/node_modules/@angular-devkit/build-angular/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Users/bokire/git/ngx-planet/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:1122:26)
    at /Users/bokire/git/ngx-planet/node_modules/@angular-devkit/build-angular/node_modules/webpack/lib/Compiler.js:1166:29
    at eval (eval at create (/Users/bokire/git/ngx-planet/node_modules/@angular-devkit/build-angular/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
/Users/bokire/git/ngx-planet/node_modules/webpack/lib/NormalModule.js:227
                        throw new TypeError(

**Comment by why520crazy** [comment]
这是因为 Angular CLI 小版本改了 Webpack 的版本导致的，示例未同步修改导致的，我会在今天修复一下。

**Comment by why520crazy** [comment]
Fixed! pull latest code and exec `npm run install` try again

**Comment by bokire** [comment]
嗯，已经可以正常启动了
